### PR TITLE
Fix minimum value, max iteration break condition, fix the use of appe…

### LINKED ISSUE #167: CG results f_minimum differs from f(minimum)
Multivariate results [type](https://github.com/JuliaOpt/Optim.jl/blob/master/src/types.jl#L24) contains `f_minimum` field that differs from the value of objective function at the minimum point:

    rosenbrock(x::Array) = (1.0 - x[1])^2 + 100.0*(x[2] - x[1]^2)^2
    optres = Optim.fminbox(Optim.DifferentiableFunction(rosenbrock),
                       zeros(2), -10*ones(2), 10*ones(2),
                       optimizer = Optim.cg, iterations = 1_000)
    println(optres.f_minimum)
    println(Optim.DifferentiableFunction(rosenbrock).f(optres.minimum))

-4.5951198447245615e-8
5.597549090140484e-17

Noticed that first when receiving negative values for minimal sum-squares etc.

I am working with the `teh/constrained` branch by @timholy but Optim-master shows the same problem.

### PR DESCRIPTION
**Pull request by pkofod**
…nd, and remove export.

Fixes #167 

I don't think it's unreasonable for `f_minimum` to return the objective function value at the minimizer, even if a barrier function was added during optimization.

<s>I also added `results.iterations >= iterations`. Before, the algorithm could run beyond the stated maximum number of iterations.</s>
I've also added separate outer and inner options.

Added `first = false` if in the `first == true` branch of the `append!` part of the code, this fixes the returned `MultivariateOptimizationResults` such that it actually adds all calls and iterations together.

### CODE REVIEW

**Comment by pkofod** [comment]
Does this make more sense @multidis ? I think it does. Thanks for the comment.

**Comment by multidis** [comment]
Sorry I am not up to date with the recent API changes, but I assume the iteration limit for `cg` can be passed inside `optimizer_o`. If that is the case then everything seems reasonable. Probably would be helpful to make a note somewhere in the future docs/readme that in the case of `fminbox`, the `iterations` argument relates to barrier function iterations and not the underlying optimizer.

Line 211 is also very helpful, thanks for taking care of that.

**Comment by pkofod** [comment]
Yes, I will make sure to thoroughly document how it is to be used before a version of this pr is merged.

**Comment by pkofod** [comment]
Test error is unrelated.

File: src/fminbox.jl [hunk 1]
```diff
@@ -177,10 +186,10 @@ function optimize{T<:AbstractFloat}(
         end
         pcp = (P, x) -> precondprep(P, x, l, u, mu)
         resultsnew = optimize(dfbox, x, optimizer(eta = eta, linesearch! = linesearch!, P = P, precondprep = pcp),
-                              OptimizationOptions(xtol=xtol, ftol=ftol, grtol=grtol, iterations=iterations,
-                                                  store_trace=store_trace, show_trace=show_trace, extended_trace=extended_trace))
+                              optimizer_o)
         if first == true
```
Comment (johnmyleswhite) [inline src/fminbox.jl]: I believe this doesn't need to be a test against `== true`, `if first` should be sufficient.

File: test/constrained.jl [hunk 2]
```diff
@@ -49,3 +49,11 @@ objective.fg!(results.minimum, g)
...
     @test abs(g[i]) < 3e-3 || (results.minimum[i] < -boxl+1e-3 && g[i] > 0) || (results.minimum[i] > boxl-1e-3 && g[i] < 0)
 end
+
+# tests for #180
+results = Optim.optimize(objective, x0, l, u, Fminbox(); iterations = 2)
+@test results.iterations == 2
+@test results.f_minimum == objective.f(results.minimum)
+
+results = Optim.optimize(objective, x0, l, u, Fminbox(); optimizer_o = OptimizationOptions(iterations = 2))
+@test results.iterations == 470
```
Comment (johnmyleswhite) [inline test/constrained.jl]: This seems troubling to me. What guarantee do we have that this number of iterations will be performed? If we improved our line search procedure, would this test break?

File: README.md [hunk 3]
```diff
@@ -278,10 +278,20 @@ x0 = [2.0, 2.0]
...
 
-This algorithm uses diagonal preconditioning to improve the accuracy, and hence is a good example of how to use `cg` with preconditioning. Only the box constraints are used. If you can analytically compute the diagonal of the Hessian of your objective function, you may want to consider writing your own preconditioner (see `nnls` for an example).
+This algorithm uses diagonal preconditioning to improve the accuracy, and hence is a good example of how to use `ConjugateGradient` with preconditioning. Only the box constraints are used. If you can analytically compute the diagonal of the Hessian of your objective function, you may want to consider writing your own preconditioner.
 
+As there are both parameters for the `Fminbox` outer iterations, and the inner `ConjugateGradient` iterations, the options syntax is a bit different from the rest of the package. All parameters regarding the outer iterations are passed as keyword arguments, and options for the interior optimizer is passed a an `OptimizationOptions` type using the keyword `optimizer_o`.
```
Comment (johnmyleswhite) [inline README.md]: Maybe write this as "there are two iterations parameters: an outer iterations parameter used to control `Fminbox` and an inner iterations parameter used to control `ConjugateGradient`. As such, the options [...]"

**Comment by johnmyleswhite** [comment]
Made some small stylistic comments. I'm a little worried about the test case, but otherwise think you should merge this whenever you want.

File: src/fminbox.jl (hunk 1 above)
Comment (pkofod) [inline src/fminbox.jl]: Yes of course.

File: test/constrained.jl (hunk 2 above)
Comment (pkofod) [inline test/constrained.jl]: I see your point. You mean the second test right? The first one should not be affected, as a better linesearch would only lower the number of inner iterations. I will have to think about another way to test it.

File: README.md (hunk 3 above)
Comment (pkofod) [inline README.md]: Thanks, the current version is bad, I see that.

**Comment by pkofod** [comment]
Thank you for the comments. I will address the test, and see if I can come up with something better.

**Comment by timholy** [comment]
I'm not following this closely (I'm on vacation), but just chiming in to say thanks for all the awesome contributions, @pkofod. The impact of your work is going to be huge.

**Comment by pkofod** [comment]
> Made some small stylistic comments. I'm a little worried about the test case, but otherwise think you should merge this whenever you want.

I am worried as well. I added a comment in case a future committer breaks the test by improving an algorithm. I know this is not optimal, but I intend to give `/test/` an overhaul in the future, and this will be the first test I revisit! Is this OK with you?



> I'm not following this closely (I'm on vacation), but just chiming in to say thanks for all the awesome contributions, @pkofod. The impact of your work is going to be huge.

Thanks, but the good old trope of standing on the shoulders of giants is more true than ever in this case. Though, I certainly do intend to throw some time after `Optim.jl` this year.
